package com.lrj.authz.admin;

import org.springframework.jdbc.core.JdbcTemplate;

import java.time.Instant;
import java.time.OffsetDateTime;
import java.time.ZoneOffset;
import java.util.List;

/**
 * 审计的 JDBC 持久化实现（Postgres；DDL 兼容 H2 便于单测）。
 * 构造时幂等建表；DB 不可达则启动失败（fail-fast——审计是安全记录，静默回退内存会造成"以为有审计其实没有"）。
 * 每次写入后按 {@code retentionMaxRows} 裁剪最旧记录（<=0 不裁剪）。
 */
public class JdbcAuditStore implements AuditStore {

    private final JdbcTemplate jdbc;
    private final int retentionMaxRows;

    public JdbcAuditStore(JdbcTemplate jdbc, int retentionMaxRows) {
        this.jdbc = jdbc;
        this.retentionMaxRows = retentionMaxRows;
        jdbc.execute("""
                CREATE TABLE IF NOT EXISTS authz_audit (
                    id     BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    at     TIMESTAMP WITH TIME ZONE NOT NULL,
                    actor  VARCHAR(255) NOT NULL,
                    action VARCHAR(64)  NOT NULL,
                    detail VARCHAR(2048) NOT NULL
                )""");
    }

    @Override
    public void record(String actor, String action, String detail) {
        jdbc.update("INSERT INTO authz_audit(at, actor, action, detail) VALUES (?, ?, ?, ?)",
                OffsetDateTime.ofInstant(Instant.now(), ZoneOffset.UTC),
                actor == null ? "-" : actor, action, detail);
        if (retentionMaxRows > 0) {
            // 保留最新 N 条：第 N 新的 id 之前的全删；行数不足 N 时子查询为 null,不删任何行。
            jdbc.update("DELETE FROM authz_audit WHERE id < (SELECT id FROM authz_audit ORDER BY id DESC "
                    + "OFFSET ? ROWS FETCH FIRST 1 ROWS ONLY)", retentionMaxRows - 1);
        }
    }

    @Override
    public List<AuditRecord> recent(int limit) {
        return jdbc.query("SELECT at, actor, action, detail FROM authz_audit ORDER BY id DESC LIMIT ?",
                (rs, i) -> new AuditRecord(
                        rs.getObject("at", OffsetDateTime.class).toInstant().toString(),
                        rs.getString("actor"), rs.getString("action"), rs.getString("detail")),
                Math.max(1, limit));
    }
}
