package com.lrj.authz.admin.audit.persistence;

import com.lrj.authz.admin.audit.port.AuditStore;

import org.springframework.jdbc.core.JdbcTemplate;

import java.time.Instant;
import java.time.OffsetDateTime;
import java.time.ZoneOffset;
import java.util.List;

/**
 * 审计的 JDBC 持久化实现（Postgres；DDL 兼容 H2 便于单测）。
 * 构造时幂等建表；DB 不可达则启动失败（fail-fast——审计是安全记录，静默回退内存会造成"以为有审计其实没有"）。
 * 每次写入后按 {@code retentionMaxRows} 裁剪最旧记录（<=0 不裁剪）。
 */
public class JdbcAuditStore implements AuditStore {

    private final JdbcTemplate jdbc;
    private final int retentionMaxRows;

    /** 显式绑定 JdbcAuditStore 的协作对象与配置，后续实例操作必须沿用同一组依赖与生命周期。 */
    public JdbcAuditStore(JdbcTemplate jdbc, int retentionMaxRows) {
        this.jdbc = jdbc;
        this.retentionMaxRows = retentionMaxRows;
        jdbc.execute(
                """
                CREATE TABLE IF NOT EXISTS authz_audit (
                    id     BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    at     TIMESTAMP WITH TIME ZONE NOT NULL,
                    actor  VARCHAR(255) NOT NULL,
                    action VARCHAR(64)  NOT NULL,
                    detail VARCHAR(2048) NOT NULL
                )""");
    }

    /** 记录当前操作审计并沿用既有保留预算，不能在后续读取时临时编造历史。 */
    @Override
    public void record(String actor, String action, String detail) {
        jdbc.update(
                "INSERT INTO authz_audit(at, actor, action, detail) VALUES (?, ?, ?, ?)",
                OffsetDateTime.ofInstant(Instant.now(), ZoneOffset.UTC),
                actor == null ? "-" : actor,
                action,
                detail);
        if (retentionMaxRows > 0) {
            // 保留最新 N 条：第 N 新的 id 之前的全删；行数不足 N 时子查询为 null,不删任何行。
            jdbc.update(
                    "DELETE FROM authz_audit WHERE id < (SELECT id FROM authz_audit ORDER BY id DESC "
                            + "OFFSET ? ROWS FETCH FIRST 1 ROWS ONLY)",
                    retentionMaxRows - 1);
        }
    }

    /** 按原倒序与调用数量读取既有审计，内存与数据库实现保持同一结果契约。 */
    @Override
    public List<AuditRecord> recent(int limit) {
        return jdbc.query(
                "SELECT at, actor, action, detail FROM authz_audit ORDER BY id DESC LIMIT ?",
                (rs, i) ->
                        new AuditRecord(
                                rs.getObject("at", OffsetDateTime.class).toInstant().toString(),
                                rs.getString("actor"),
                                rs.getString("action"),
                                rs.getString("detail")),
                Math.max(1, limit));
    }
}
