import { test } from 'node:test'
import assert from 'node:assert/strict'
import { randomUUID } from 'node:crypto'
import { validateReviewDetail, validateReviewList, validateReviewResponsibles, canReviewDecide } from '../src/governance/accessReview.ts'
const id = randomUUID(), member = randomUUID(), responsible = randomUUID(), grant = randomUUID(), now = new Date().toISOString(), hash = 'a'.repeat(64)
const original = () => ({ grant: { grant_id: grant, member_id: member, generation: 1, group_id: null, role_id: randomUUID(), role_code: 'reader', role_version: 1, capabilities: ['shop.read'], scope: 'TENANT_ALL', scope_rule: null, source_type: 'DIRECT', source_id: randomUUID(), valid_from: now, valid_to: now, grant_state: 'ACTIVE', effective_state: 'ACTIVE', grant_version: 1, operation_id: randomUUID(), policy_state: 'READY', directory_state: 'READY' }, current_generation: true, group_relations: [], revocation_receipt: null })
function detail() { const source = original(); return { id, membership_id: member, responsible_membership_id: responsible, state: 'RUNNING', version: 1, created_at: now, updated_at: now, target_generation: 1, original_basis_hash: hash, responsible_generation: 1, reason: '调岗来源人工复核', created_by: responsible, creator_generation: 1, responsible_qualified: true, can_decide: true, items: [{ id: randomUUID(), grant_id: grant, original: source, original_hash: hash, state: 'PENDING', version: 1, reason: null, revoke_command: randomUUID(), confirmed_operation_id: null }], current_report: { target: { membership_id: member, status: 'ACTIVE', generation: 1, version: 1, principal_status: 'ACTIVE', principal_version: 1, valid_from: now, valid_to: null }, directories: [], directory_sources: [], changes: [], sources: [source], next_change_cursor: null, next_source_cursor: null, basis_hash: hash, complete: true, checked_at: now } } }
test('fixed original source and current report are validated independently', () => { const d = detail(); assert.equal(validateReviewDetail(d, id), d); assert.equal(canReviewDecide(d, d.items[0]), true); const changed = structuredClone(d); changed.current_report.target.generation = 2; assert.equal(validateReviewDetail(changed, id), changed); assert.equal(canReviewDecide(changed, changed.items[0]), false) })
test('acceptance cannot become completed review or revoked item without real operation proof', () => { for (const change of [d => { d.state = 'COMPLETED' }, d => { d.items[0].state = 'REVOKED'; d.items[0].reason = '撤权' }, d => { d.items[0].state = 'WAIT_REVOKE'; d.items[0].reason = '撤权'; d.items[0].confirmed_operation_id = randomUUID() }]) { const d = detail(); change(d); assert.throws(() => validateReviewDetail(d, id)) } const d = detail(); d.items[0].state = 'WAIT_REVOKE'; d.items[0].reason = '真实撤权处理中'; assert.equal(validateReviewDetail(d, id), d); assert.equal(canReviewDecide(d, d.items[0]), false) })
test('foreign task, missing qualification, duplicate source and unknown states fail closed', () => { for (const change of [d => { d.id = randomUUID() }, d => { delete d.responsible_qualified }, d => { d.responsible_qualified = false }, d => { d.items.push(structuredClone(d.items[0])) }, d => { d.items[0].state = 'SUCCESS' }, d => { d.items[0].original.grant.member_id = randomUUID() }]) { const d = detail(); change(d); assert.throws(() => validateReviewDetail(d, id)) } })
test('bounded lists and current responsible generations cannot become implicit authority', () => { assert.deepEqual(validateReviewResponsibles([{ membership_id: responsible, generation: 1, version: 1 }]), [{ membership_id: responsible, generation: 1, version: 1 }]); assert.throws(() => validateReviewResponsibles([{ membership_id: responsible, generation: 0, version: 1 }])); assert.throws(() => validateReviewList({ items: Array(21).fill(detail()), next_cursor: null })); const d = detail(); d.state = 'CANCELLED'; d.items[0].state = 'CANCELLED'; d.items[0].reason = '停止未处理'; assert.equal(validateReviewDetail(d, id), d); assert.equal(canReviewDecide(d, d.items[0]), false) })
